AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Video Stream Extraction API - AWS Lambda Deployment

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: python3.9
    Environment:
      Variables:
        PYTHONUNBUFFERED: '1'

Resources:
  VideoExtractorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: main.handler
      Events:
        ExtractApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  
  FunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt VideoExtractorFunction.Arn
